name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read release notes
        id: notes
        run: |
          TAG=${GITHUB_REF##*/}
          RN_FILE="RELEASE_NOTES_${TAG}.md"
          if [ ! -f "$RN_FILE" ]; then RN_FILE="RELEASE_NOTES_${TAG%.0}.md"; fi || true
          if [ -f "$RN_FILE" ]; then cat "$RN_FILE" > /tmp/release_notes || true; else echo "Release $TAG" > /tmp/release_notes; fi
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/release_notes >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
